Fixes#149
PolymerElements/paper-drawer-panel pull request #158
Opened 2016-12-19 00:22 UTC by thisoares

Fixes issue #149. Disabled the animation transition while handling rightDrawer changes.

2016-12-19 18:15 UTC, blasten requested changes

2016-12-19 18:15 UTC, blasten commented on paper-drawer-panel.html
> +          this._forceReflow(this.$.drawer);
This is bad for performance. You can also set `this._transition=transition` in a `requestAnimationFrame` block.  Also, you can check the old value of `rightDrawer` from `_rightDrawerChanged: function(newRightDrawer, oldRightDrawer)` and if it's `undefined`, you can can skip doing all this setup.

2016-12-20 17:52 UTC, blasten approved these changes

2016-12-20 17:54 UTC, blasten commented
@thisoares thanks for the update. A few tests are failing. Probably those assertions need to go inside a rAF callback.

2016-12-20 18:01 UTC, thisoares commented
I agree that it is bad for performance. I changed the proposed solution. Instead of disabling the transition when changing the rightDrawer attribute, I disabled the drawer transition and enable it only when opening/closing the drawer.

2016-12-20 18:28 UTC, blasten commented
LGTM. Thanks!

2016-12-20 18:28 UTC, merged