Automatic format!
PolymerElements/paper-drawer-panel pull request #176
Opened 2018-04-10 21:54 UTC by e111077

Runs the experimental autoformatter [webmat](https://github.com/PolymerLabs/webmat) which runs clang-format on js files and makes it so that it can run on HTML files. Please look through this PR with `?w=1` in the diff to make sure that no logic was changed.

What has changed?
You can run the formatter on the whole project by running `npm run format` and ex/include files from the formatter, and enter your custom clang-format config in a formatconfig.json see webmat readme for more!

2018-04-10 23:08 UTC, keanulee requested changes

2018-04-10 23:08 UTC, keanulee commented on demo/index.html
> +      }
Missing semicolon causing weird indentation below

2018-04-10 23:40 UTC, dfreedm approved these changes
LGTM for travis config

2018-04-11 16:58 UTC, keanulee approved these changes

2018-04-11 18:54 UTC, merged